### ISSUE TITLE
Impossible to change the theme

### ISSUE THREAD

**Issue by kickdev** [wieslawsoltes/Avalonia.ThemeManager#1]
From Example 2, the item is not available. When compiling Core2D. Sampling doesn't work there either.
![image](https://user-images.githubusercontent.com/10669667/71597667-215a4500-2b55-11ea-9c35-b72769d96879.png)
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Command": "Could not find CLR property 'ApplyTheme' on 'Avalonia.ThemeManager.Theme'" (Avalonia.Controls.MenuItem #39696553)
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Command": "Could not find CLR property 'ApplyTheme' on 'Avalonia.ThemeManager.Theme'" (Avalonia.Controls.MenuItem #63406242)
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Command": "Could not find CLR property 'ApplyTheme' on 'Avalonia.ThemeManager.Theme'" (Avalonia.Controls.MenuItem #511887)
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Command": "Could not find CLR property 'ApplyTheme' on 'Avalonia.ThemeManager.Theme'" (Avalonia.Controls.MenuItem #3048957)
If use **{Binding ThemeSelected.ApplyTheme}**
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Header": "Could not find CLR property 'Name' on 'Avalonia.ThemeManager.ThemeSelector'" (Avalonia.Controls.MenuItem #51198184)
[Binding] Error in binding to "Avalonia.Controls.MenuItem"."Command": "Could not find CLR property 'ThemeSelected' on 'Avalonia.ThemeManager.ThemeSelector'" (Avalonia.Controls.MenuItem #51198184)

**Comment by wieslawsoltes** [comment]
@kickdev Will be fixed in 0.9.1 release.

**Comment by wieslawsoltes** [comment]
Released 0.9.1
