### ISSUE TITLE
Latest download gives a empty form

### ISSUE THREAD

**Issue by JamRemco** [wieslawsoltes/Avalonia.ThemeManager#2]
\Avalonia.ThemeManager-0.9.4
![image](https://user-images.githubusercontent.com/58340108/76780481-67ff2900-67ad-11ea-8586-d97130d83bf0.png)

**Comment by wieslawsoltes** [comment]
That's just sample app. It doesn't have any content  just menu. Avalonia.ThemeManager is just a library.

**Comment by JamRemco** [comment]
O now i see it should be theme editor. my bad
