### ISSUE TITLE
The Style already has a parent

### ISSUE THREAD

**Issue by 3400442579** [wieslawsoltes/Avalonia.ThemeManager#3]
//Open new window
   public void button_Click(object sender, RoutedEventArgs e)
        {
            TestWindow testWindow = new TestWindow();
            testWindow.Show();
        }

 public class TestWindow : Window
    {
        public TestWindow()
        {
            this.InitializeComponent();
            this.AttachDevTools();
            App.Selector?.EnableThemes(this); //  Error   The Style already has a parent.
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }

**Comment by wieslawsoltes** [comment]
Known issue.

**Comment by trippsc2** [comment]
Any ideas on how this can be resolved?  I'd like to update my project to Avalonia 0.10 to resolve a Linux issue with Save/Open dialog boxes that I'm experiencing, but doing so breaks ThemeManager.

**Comment by wieslawsoltes** [comment]
This is issue with Avalonia framework.
