### ISSUE TITLE
Fluent themes broken in AvaloniaApp

### ISSUE THREAD

**Issue by PureAsbestos** [wieslawsoltes/Avalonia.ThemeManager#9]
Using the latest master, switching to a Fluent theme when running AvaloniaApp results in an unhandled exception:
```
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

Inner Exception
KeyNotFoundException: Static resource 'SystemControlBackgroundAccentBrush' not found.
```

Adding these includes to App.axaml:
```
<StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/Base.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseLight.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseDark.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/AccentColors.xaml"/>
```
Fixes the error, but certain elements (the calendar, certain pieces of text, etc.) will always use whichever fluent style was included last, rather than using the selected one.

(Running on Win10, VS2022)

**Comment by wieslawsoltes** [comment]
Theme system was changed in v11 of Avalonia, this no longer applies.
